# Generated by Django 3.2.6 on 2023-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150, verbose_name='Destination')),
                ('yos', models.CharField(max_length=50, verbose_name='Year of Study')),
                ('month', models.CharField(max_length=150, verbose_name='Year of Month')),
                ('los', models.CharField(max_length=150, verbose_name='level of study')),
                ('los2', models.CharField(max_length=150, verbose_name='level of study')),
                ('firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('phono', models.CharField(max_length=150, verbose_name='Phone Number')),
                ('passport', models.CharField(max_length=150, verbose_name='Passport')),
                ('ept', models.CharField(max_length=50, verbose_name='Have you appeared for IELTS/TOEFL or any English proficiency test?')),
                ('toe', models.CharField(max_length=50, verbose_name='Type of Exam')),
                ('Listing_Score', models.CharField(max_length=150, verbose_name='Listing_Score')),
                ('Reading_Score', models.CharField(max_length=150, verbose_name='Reading_Score')),
                ('Writing_Score', models.CharField(max_length=150, verbose_name='Writing_Score')),
                ('Speaking_Score', models.CharField(max_length=150, verbose_name='Speaking_Score')),
                ('Overall_Score', models.CharField(max_length=150, verbose_name='Overall_Score')),
                ('examname', models.CharField(max_length=150, verbose_name='Exam Name')),
                ('total_score', models.CharField(max_length=150, verbose_name='Total Score')),
                ('fund', models.CharField(max_length=150, verbose_name='Fund')),
                ('budget', models.CharField(max_length=150, verbose_name='Budget')),
                ('tenp', models.CharField(max_length=150, verbose_name='10TH Percentage')),
                ('tenpass', models.CharField(max_length=150, verbose_name='10th Passing')),
                ('tenstate', models.CharField(max_length=150, verbose_name='Syllabus')),
                ('twep', models.CharField(max_length=150, verbose_name='12TH Percentage')),
                ('twepass', models.CharField(max_length=150, verbose_name='12th Passing')),
                ('twestate', models.CharField(max_length=150, verbose_name='Syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
    ]
