# Generated by Django 3.2.6 on 2023-04-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Fullname')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('mode', models.CharField(max_length=50, verbose_name='Mode')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
